---
output:
  html_document: default
  pdf_document: default
---
```{r}
rm(list = ls())
```

```{r}
source('utilities.R')
# TODO: also parse down the demographic variables?
data_dictionary <- read.csv('../../data/final_data_dictionary.csv')
data <- read.csv('../../data/final_data.csv')
```

```{r}
# select outcome
outcomes <- data_dictionary %>% 
  filter(outcome == 1) %>% 
  dplyr::select(column_name) %>% 
  mutate(column_name = as.character(column_name)) %>% 
  pull()
```

```{r Methodology options}
opts <- data.frame("use_sdoh_scores" = c(1, 0, 0),
                      "use_sdoh_raw" = c(0, 1, 0),
                      "use_dems" = c(1, 1, 1))

# TODO: not sure if this cross join is going to work out
opts <- merge(opts, data.frame("methodology" = c("rf proximity","euclidean")),
              all = TRUE)

opts$meth_num <- row_number(opts$use_dems)
# TODO: eventually will add a remove modifiable, relevant option
# TODO: loop through prediction algorithms & just euclidean distance

# both the aggregate score and the inputs should not be true at the same time
print(opts[opts$use_sdoh_scores & opts$use_sdoh_raw,])
print(opts)
```

```{r}
# TODO: select which counties to look at: Boulder, smaller one, etc. rather than just first 5

implement_methodology <- function(row, outcomes, data, data_dictionary){
  # TODO: loop through methodologies
  use_sdoh_scores <- as.numeric(row[1])
  use_sdoh_raw <- as.numeric(row[2])
  use_dems <- as.numeric(row[3])
  methodology <- row[4]
  meth_num <- as.numeric(row[5])
  
  # TODO: could loop through a subset of the opts dataframe
  for(use_outcome in outcomes){
    print(paste("Outcome:", use_outcome))
    
    orig_data <- data %>% 
      filter(!is.na(!!rlang::sym(use_outcome)))
    
    ## Select variables to match on, limit data to these variables, and replace NAs
    use_data <- select_distance_columns(data = orig_data, data_dictionary = data_dictionary,
                                        sdoh_scores = use_sdoh_scores, sdoh_raw = use_sdoh_raw,
                                        outcome = use_outcome, dem = use_dems)
    
    ## Get distance matrix using methodology specified
    distancem <- county_distance(use_data, methodology, use_outcome)
      
    # for(county_num in c(1:5)){
    for(county_num in c(1:5)){
      print(paste("County Number:", county_num))
    
      data <- select_county(orig_data, distancem, county_num)
      
      ## Evaluate the methodology:
      # Look at the radar charts in order of county similarity
      # How similar are health outcomes of the top 5 most similar or similar within a certain distance? 
      # They should have a median close to the county in question
      results <- evaluate_methodology(data, use_outcome)
      results <- c(county_num, use_outcome, methodology, meth_num, results)
      results_df = as.data.frame(matrix(unlist(results), nrow = 1))
      colnames(results_df) <- c('county','outcome','methodology','meth_num','pct_diff_from_county_med','pct_reduced_sd')
        
      if(use_outcome == outcomes[1]){
        full_results <- results_df
      } else {
        full_results <- full_results %>% 
          rbind(results_df)
      }
      
    }
  }
  full_results[,!names(full_results) %in% c("methodology","outcome")] <- as.numeric(as.character(unlist(full_results[,!names(full_results) %in% c("methodology","outcome")])))
  return(full_results)
}

full_results <- apply(opts, 1, implement_methodology, outcomes, data, data_dictionary)

```

```{r}
results <- bind_rows(full_results, .id = "column_label")
print(results)

# average metrics across county by outcome to evaluate results of different methodologies
summ_results <- results %>% 
  group_by(outcome, methodology, meth_num, column_label) %>% 
  dplyr::summarise_all(funs(median)) %>% 
  arrange(outcome) %>% 
  select(outcome, methodology, meth_num, pct_diff_from_county_med, pct_reduced_sd)

best_results <- summ_results %>% 
  group_by(outcome) %>% 
  dplyr::summarise(best_pct_diff = min(pct_diff_from_county_med),
                   best_pct_sd = max(pct_reduced_sd))

best_results <- best_results %>% 
  merge(summ_results, by.x = c("outcome","best_pct_diff"),
        by.y = c("outcome","pct_diff_from_county_med")) %>% 
  select(outcome, meth_num, best_pct_sd) %>% 
  rename(best_meth_pct_diff = meth_num) %>% 
  merge(summ_results, by.x = c("outcome","best_pct_sd"),
        by.y = c("outcome","pct_reduced_sd")) %>% 
  select(outcome, best_meth_pct_diff, meth_num) %>% 
  rename(best_meth_pct_sd = meth_num)
best_results

best_results %>% 
  group_by(best_meth_pct_diff) %>% 
  dplyr::summarise(n = n())
# 1 or 5
best_results %>% 
  group_by(best_meth_pct_sd) %>% 
  dplyr::summarise(n = n())
# 3 or 5

opts

```